version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: task_postgres
    environment:
      POSTGRES_USER: Vexced
      POSTGRES_PASSWORD: Zaphkiel987*
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
